travis:
  secure:
    BINSTAR_TOKEN: GQ5BBInl1smFGBPmhbF6+XUB1CGNyXEk6N6lTDRDYQTlYToyUvi2CysZBoztqnwOwrKwAhMrza3iGR1Cs2Q4WkI/xf+U6TUOP0QJ1n03gf+B454XrvjjZ6E9UUXoprRq3MYb4rmH2H5s+B0bt8kKjjGuY/fPcMruPc0Lc7onIB5m/D75jNb9fhBWCwkErCVSygZ2CIq6qqoJQCMXBYuQwj1zX+2lhOLs8CNHNPhQHob6FiiOcn4EC18g7bBc0BMzEjVNm1SI84OukcBPD+BxqZ+tYnlHgbFWD7SiBvZb+T3B7Eux2udTspU65JrerkFseOc7VbV8GbaOco0t4J1Ogk4mNsAZsZPeo+nbtYKXjYe7iO2vVfbOOntwicaf8JJWFW3Moah9tMNYmT+/ckyEtPlZvot/DU+ztITNh1BaI45XfnNWy82AalqpAokyUKUwTIbIGiwdZvi/fUSILdlBm/pYQ8ls28KGvCcO6aRk/xER7qEhPdiR2+OdgS76j759iidv+FXaq/pa0zhWDmrc4Wy/IZfYcimI10ycc03TC/mp9+cZjwz40V/uD6zSUkBNhXjuWi+GfH3JX0WiI5fso7pAx152adVZwQeKugfp3AqfWC0mfOp7jDwgPOENxqA6awRcQiVITYeXFgJ00lwclQrw4pd6nsmwPnqzpAAUK98=
conda_forge_output_validation: true
bot:
  automerge: true
